#!/usr/bin/env bash
# A Bash script containing commands to automatically configure a Ubuntu.
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/JamesOnoka permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
