#!/bin/bash
# Update package list and install HAProxy

apt-get update -y
apt-get install -y haproxy
sed -i "s|ENABLED=0|ENABLED=1|g" /etc/default/haproxy
echo -e "frontend front_1
\tbind :80
\tmode http
\tdefault_backend back_1
backend back_1
\tmode http
\tbalance roundrobin
\toption forwardfor
\tserver 27432-web-01 3.80.19.175:80 check
\tserver 27432-web-02 34.239.253.118:80 check" | tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
