#!/usr/bin/env bash
# A script that displays "Best School" 10 times with "Hi" on the 9 iteration.

x=1
while [ $x -le 10 ];
do
	if [ $x -eq 9 ];
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	let x++
done
