#!/usr/bin/env bash
# A script that displays "Best School" 10 times with "Hi" on the 9 iteration.

x=0

while [ $x -lt 10 ];
do
	if [ $x -eq 8 ];
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((x++))
done
