#!/usr/bin/env bash
# A script that loops from 1 to 10.

x=1
while [ $x -lt 11 ];
do
	if [ $x  -eq 4 ];
	then
		echo "bad luck"

	elif [ $x = 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
