#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes.

HPD=0
MPHR=1

while [ $HPD -le 12 ];
do
	echo "HPD: $HPD"
	while [ $MPHR -le 59 ];
	do
		echo "$MPHR"
		((MPHR++))
	done
	MPHR=1
	((HPD++))
done
