#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes.

Hour=0
MPHR=1

while [ $Hour -le 12 ];
do
	echo "Hour: $Hour"
	while [ $MPHR -le 59 ];
	do
		echo "$MPHR"
		((MPHR++))
	done
	MPHR=1
	((Hour++))
done
