#!/usr/bin/env bash
# A Script that changes localhost resolves to 127.0.0.2.
# A script that changes facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i "s/^127.0.0.1 localhost$/127.0.0.2 localhost/" ~/hosts.new
sed -i '$/^.*\bfacebook.com\b.*$/8.8.8.8 facebook.com' ~/hosts.new

cp -f ~/hosts.new /etc/hosts
